import 'package:flutter/material.dart';
import '../features/shop/models/product.dart';

final List<Product> mockTrendingProducts = [
  Product(
    id: 't1',
    name: 'Air Max Streak',
    brand: 'Nike · Orange',
    price: 89.99,
    oldPrice: 129.99,
    rating: 4.5,
    reviews: '2.1k',
    emoji: '👟',
    bgColor: const Color(0xFFFFF0EB),
    discountBadge: '-30%',
  ),
  Product(
    id: 't2',
    name: 'ANC Pro Headphones',
    brand: 'Sony · Midnight',
    price: 199.99,
    oldPrice: 249.99,
    rating: 4.0,
    reviews: '980',
    emoji: '🎧',
    bgColor: const Color(0xFFEBF4FF),
    discountBadge: '-20%',
  ),
  Product(
    id: 't3',
    name: 'Smart Watch X5',
    brand: 'Apple · Silver',
    price: 329.00,
    rating: 5.0,
    reviews: '4.2k',
    emoji: '⌚',
    bgColor: const Color(0xFFEDFFF4),
  ),
  Product(
    id: 't4',
    name: 'Leather Tote Bag',
    brand: 'Zara · Tan',
    price: 59.99,
    oldPrice: 69.99,
    rating: 3.5,
    reviews: '543',
    emoji: '👜',
    bgColor: const Color(0xFFFFF5EB),
    discountBadge: '-15%',
  ),
  Product(
    id: 't5',
    name: 'Mechanical Keyboard',
    brand: 'Keychron · Grey',
    price: 110.00,
    rating: 4.8,
    reviews: '1.2k',
    emoji: '⌨️',
    bgColor: const Color(0xFFF4EBFF),
  ),
  Product(
    id: 't6',
    name: 'Wireless Mouse',
    brand: 'Logitech · Black',
    price: 45.00,
    rating: 4.6,
    reviews: '3.4k',
    emoji: '🖱️',
    bgColor: const Color(0xFFFFF0EB),
  ),
  Product(
    id: 't7',
    name: 'Coffee Maker Pro',
    brand: 'Breville · Steel',
    price: 450.00,
    oldPrice: 500.00,
    rating: 4.9,
    reviews: '8k',
    emoji: '☕',
    bgColor: const Color(0xFFEBF4FF),
    discountBadge: '-10%',
  ),
  Product(
    id: 't8',
    name: 'Yoga Mat',
    brand: 'Lululemon · Pink',
    price: 68.00,
    rating: 4.7,
    reviews: '2.2k',
    emoji: '🧘‍♀️',
    bgColor: const Color(0xFFEDFFF4),
  ),
  Product(
    id: 't9',
    name: 'Portable Charger',
    brand: 'Anker · White',
    price: 39.99,
    rating: 4.4,
    reviews: '5k',
    emoji: '🔋',
    bgColor: const Color(0xFFFFF5EB),
  ),
  Product(
    id: 't10',
    name: 'Desk Lamp',
    brand: 'Xiaomi · White',
    price: 25.00,
    rating: 4.3,
    reviews: '800',
    emoji: '💡',
    bgColor: const Color(0xFFF4EBFF),
  ),
];

final List<Product> mockNewArrivals = [
  Product(
    id: 'n1',
    name: 'Mini Drone',
    brand: 'DJI · Grey',
    price: 299.00,
    rating: 4.9,
    reviews: '120',
    emoji: '🚁',
    bgColor: const Color(0xFFEDFFF4),
    discountBadge: 'NEW',
  ),
  Product(
    id: 'n2',
    name: 'Action Camera',
    brand: 'GoPro · Black',
    price: 399.00,
    rating: 4.7,
    reviews: '85',
    emoji: '📷',
    bgColor: const Color(0xFFF4EBFF),
    discountBadge: 'NEW',
  ),
  Product(
    id: 'n3',
    name: 'Running Shorts',
    brand: 'Under Armour',
    price: 35.00,
    rating: 4.5,
    reviews: '40',
    emoji: '🩳',
    bgColor: const Color(0xFFFFF0EB),
  ),
  Product(
    id: 'n4',
    name: 'Polarized Shades',
    brand: 'Ray-Ban · Gold',
    price: 155.00,
    rating: 4.8,
    reviews: '210',
    emoji: '🕶️',
    bgColor: const Color(0xFFEBF4FF),
  ),
  Product(
    id: 'n5',
    name: 'Travel Backpack',
    brand: 'Osprey · Blue',
    price: 180.00,
    rating: 4.6,
    reviews: '65',
    emoji: '🎒',
    bgColor: const Color(0xFFFFF5EB),
  ),
  Product(
    id: 'n6',
    name: 'Ceramic Planter',
    brand: 'IKEA · White',
    price: 12.99,
    rating: 4.2,
    reviews: '15',
    emoji: '🪴',
    bgColor: const Color(0xFFEDFFF4),
  ),
  Product(
    id: 'n7',
    name: 'Water Bottle',
    brand: 'Yeti · Cyan',
    price: 45.00,
    rating: 4.9,
    reviews: '330',
    emoji: '💧',
    bgColor: const Color(0xFFEBF4FF),
  ),
  Product(
    id: 'n8',
    name: 'Smart Scale',
    brand: 'Withings · Glass',
    price: 99.00,
    rating: 4.5,
    reviews: '90',
    emoji: '⚖️',
    bgColor: const Color(0xFFF4EBFF),
  ),
  Product(
    id: 'n9',
    name: 'Wireless Earbuds',
    brand: 'Samsung · Purple',
    price: 149.00,
    rating: 4.4,
    reviews: '110',
    emoji: '🎧',
    bgColor: const Color(0xFFFFF0EB),
  ),
  Product(
    id: 'n10',
    name: 'Winter Beanie',
    brand: 'Carhartt · Brown',
    price: 19.99,
    rating: 4.8,
    reviews: '400',
    emoji: '🧢',
    bgColor: const Color(0xFFFFF5EB),
  ),
];

final List<Map<String, dynamic>> mockCategories = [
  {
    'icon': '👟',
    'label': 'Shoes',
    'color': const Color(0xFFFFF0EB),
    'active': true,
  },
  {
    'icon': '👗',
    'label': 'Fashion',
    'color': const Color(0xFFEBF4FF),
    'active': false,
  },
  {
    'icon': '💻',
    'label': 'Tech',
    'color': const Color(0xFFEDFFF4),
    'active': false,
  },
  {
    'icon': '🏠',
    'label': 'Home',
    'color': const Color(0xFFFFF5EB),
    'active': false,
  },
  {
    'icon': '💄',
    'label': 'Beauty',
    'color': const Color(0xFFF4EBFF),
    'active': false,
  },
  {
    'icon': '⌚',
    'label': 'Accessories',
    'color': const Color(0xFFEBF4FF),
    'active': false,
  },
  {
    'icon': '🎧',
    'label': 'Headphones &\nEarbuds',
    'color': const Color(0xFFFFF0EB),
    'active': false,
  },
];

final List<Map<String, String>> mockCarouselData = [
  {
    'image':
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop',
    'tag': 'FLASH SALE',
    'title': 'Up to 50% OFF\nSneakers',
  },
  {
    'image':
        'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    'tag': 'NEW ARRIVAL',
    'title': 'Premium Audio\nExperience',
  },
  {
    'image':
        'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop',
    'tag': 'TECH DEALS',
    'title': 'Smart Watches\nCollection',
  },
  {
    'image':
        'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=800&auto=format&fit=crop',
    'tag': 'TRENDING',
    'title': 'Designer Bags\n& Accessories',
  },
];
